[pr_reviewer]
# Требования к ревью
require_score_review = true
require_tests_review = true
require_security_review = true

# Ограничения
max_files_to_review = 150
max_lines_to_review = 15000

# Доп. инструкции
extra_instructions = """
СТРОИТЕЛЬНЫЙ ПРОЕКТ - ЭТАП 1 (ФОКУС НА TZDReader):

✅ ОСТАВИТЬ:
- app/agents/tzd_reader/ (единственный агент)
- app/parsers/ (документные парсеры)
- app/core/ (базовые сервисы, orchestrator, llm_service)
- knowledge/ (база знаний)
- prompts/ (промпты для TZDReader)

❌ УДАЛИТЬ:
- Все остальные агенты кроме tzd_reader/
- Хвосты от удалённых агентов (imports, тесты, ссылки)
- Любые неиспользуемые файлы и зависимости
- Старые роутеры, сервисы или код, который не связан с TZDReader

⚙️ ЦЕЛЬ:
- Чистая архитектура вокруг одного агента TZDReader
- Подготовка базы для будущих агентов (beads-архитектура)
- Код должен быть лёгким для расширения
"""

[pr_improve]
# Предложения улучшений
max_suggestions = 15
include_security_suggestions = true
extra_instructions = """
Оптимизация и улучшения должны касаться только TZDReader и базовой инфраструктуры.
Запрещено предлагать улучшения для удалённых агентов или legacy-кода.
"""

[pr_test]
# Настройки тестов
testing_framework = "pytest"
extra_instructions = """
Добавлять и поддерживать тесты только для агента TZDReader и его зависимостей.
Удалить или переписать тесты, которые ссылаются на другие агенты.
"""
