services:
  - type: web
    name: concrete-agent
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: pip install -r requirements.txt && mkdir -p outputs
    
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: RENDER_SERVICE_ID
        sync: false
      - key: CLAUDE_MODEL
        value: claude-3-sonnet-20240229
      - key: USE_CLAUDE
        value: "true"
      - key: LOG_LEVEL
        value: "INFO"
      - key: MAX_FILE_SIZE
        value: "52428800"
      - key: MAX_DOCUMENTS
        value: "10"
      - key: UPLOAD_DIR
        value: "uploads"
      - key: LOGS_DIR
        value: "logs"
      - key: ALLOWED_EXTENSIONS
        value: ".pdf,.docx,.doc,.txt,.xml,.xls,.xlsx,.csv"
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.11.9"
