[agent]
name = "DrawingParserAgent"
version = "1.0.0"
enabled = true
description = "Drawing parser - analyzes construction drawings and blueprints"

[contracts]
inputs_schema = "DWG/DXF/PDF drawing files"
outputs_schema = "JSON with materials, dimensions, volumes, and construction elements"

[capabilities]
extracts = ["materials", "dimensions", "volumes", "construction_elements"]
depends_on = ["knowledge.MATERIALS", "knowledge.CONCRETE_GRADES"]

[runtime]
entrypoint = "app/agents/drawing_parser/agent.py:DrawingParserAgent"
timeout_seconds = 120
