[agent]
name = "TZDReaderAgent"
version = "1.0.0"
enabled = true
description = "TZD Reader - analyzes technical assignment documents"

[contracts]
inputs_schema = "PDF/DOCX/TXT technical document files"
outputs_schema = "JSON with project object, requirements, norms, constraints, environment, functions"

[capabilities]
extracts = ["project_requirements", "technical_norms", "constraints", "project_functions"]
depends_on = ["llm_service", "knowledge.NORMS"]

[runtime]
entrypoint = "app/agents/tzd_reader/agent.py:TZDReaderAgent"
timeout_seconds = 120
