name: Deploy with Claude Fixer (Auto Mode with Limit)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Render
        id: render-deploy
        run: |
          echo "Triggering Render deploy..."
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json"

      - name: Get Render logs
        if: failure()
        run: |
          curl -s "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/logs" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" > render_logs.txt
          cat render_logs.txt

      - name: Ask Claude to fix errors
        if: failure()
        run: |
          RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
            -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"claude-3-opus-20240229\",
              \"max_tokens\": 1000,
              \"messages\": [
                {\"role\": \"user\", \"content\": \"Here are the Render deploy logs, fix the errors in code and propose a patch (return unified diff format):\n$(cat render_logs.txt)\"}
              ]
            }")
          echo "$RESPONSE" > claude_fix.json
          cat claude_fix.json

      - name: Apply Claude patch automatically
        if: failure()
        run: |
          echo "Applying Claude fix..."
          PATCH=$(jq -r '.content[0].text' claude_fix.json)
          echo "$PATCH" > claude_patch.diff
          git apply claude_patch.diff || echo "Failed to apply patch"
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Auto-fix by Claude from Render logs"
          git push origin main

      - name: Track failure attempts
        if: failure()
        run: |
          echo "Handling failure count..."
          ATTEMPT_FILE=".deploy_failures"
          if [ -f $ATTEMPT_FILE ]; then
            COUNT=$(cat $ATTEMPT_FILE)
          else
            COUNT=0
          fi
          COUNT=$((COUNT+1))
          echo $COUNT > $ATTEMPT_FILE
          echo "Failure attempt: $COUNT"

          if [ "$COUNT" -ge 3 ]; then
            echo "Reached maximum 3 automatic fixes. Stopping auto-fix."
            exit 1
          fi
