name: Deploy to Render

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          set -o pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt 2>&1 | tee build.log

      - name: Deploy to Render
        id: render-deploy
        run: |
          echo "Triggering Render deploy..." | tee -a build.log
          curl -s -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
               -H "Content-Type: application/json" | tee -a build.log

      - name: Create deployment failure issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let logs = '';
            try {
              logs = fs.readFileSync('build.log', 'utf8');
            } catch (error) {
              logs = 'No build logs available';
            }

            const issueTitle = `🚨 Deployment Failed - ${new Date().toISOString().split('T')[0]}`;
            const issueBody = `
            ## Deployment Failure Report

            **Workflow:** ${context.workflow}
            **Run ID:** ${context.runId}
            **Commit:** ${context.sha.substring(0, 7)}
            **Branch:** ${context.ref.replace('refs/heads/', '')}

            ### Build Logs
            \`\`\`
            ${logs}
            \`\`\`

            ### Next Steps
            1. Review the logs above
            2. Fix the identified issues
            3. Push changes to trigger a new deployment

            @claude Please analyze these deployment logs and suggest fixes.

            *This issue was created automatically by the deployment workflow.*
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['bug', 'deployment', 'auto-created']
            });
