name: Deploy Backend to Render

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - 'backend/Dockerfile'
      - 'render.yaml'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Validate backend imports
        run: |
          pip install -q -r requirements.txt
          cd /home/runner/work/concrete-agent/concrete-agent
          python3 -c "from backend.app.main import app; print('✅ Backend imports successfully with full package path')"

      - name: Deploy to Render
        run: |
          echo "Triggering Render backend deploy..."
          response=$(curl -s -w "\n%{http_code}" -X POST \
               "https://api.render.com/v1/services/${{ secrets.RENDER_BACKEND_SERVICE_ID }}/deploys" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
               -H "Content-Type: application/json")
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "Response body: $body"
          echo "HTTP status code: $http_code"
          
          if [ "$http_code" -ne 201 ] && [ "$http_code" -ne 200 ]; then
            echo "Deploy trigger failed with status $http_code"
            exit 1
          fi
          
          echo "Deploy triggered successfully"

      - name: Verify deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          
          echo "Checking backend health..."
          for i in {1..10}; do
            if curl -f -s "https://concrete-agent.onrender.com/health" | grep -q "healthy"; then
              echo "Backend is healthy!"
              
              # Test critical endpoints
              echo "Testing /status endpoint..."
              curl -s "https://concrete-agent.onrender.com/status" | jq .
              
              echo "Testing /docs endpoint..."
              curl -s -I "https://concrete-agent.onrender.com/docs" | head -1
              
              exit 0
            fi
            echo "Attempt $i/10 failed, waiting 10 seconds..."
            sleep 10
          done
          
          echo "Warning: Health check timed out, but deploy may still succeed"
          exit 1
