name: Deploy Backend to Render

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'render.yaml'
      - '.github/workflows/render_deploy.yml'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then
            echo "❌ RENDER_API_KEY secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.RENDER_BACKEND_SERVICE_ID }}" ]; then
            echo "❌ RENDER_BACKEND_SERVICE_ID secret is not set"
            exit 1
          fi
          echo "✅ All required secrets are set"
      
      - name: Create temporary .env for validation
        run: |
          echo "Creating temporary .env for import validation..."
          cat > .env << EOF
          ANTHROPIC_API_KEY=test-key-for-validation
          OPENAI_API_KEY=test-key
          CLAUDE_MODEL=claude-sonnet-4-20250514
          ENABLE_WORKFLOW_A=true
          ENVIRONMENT=development
          EOF
          echo "✅ Temporary .env created"
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install -q -r requirements.txt
          echo "✅ Dependencies installed"
      
      - name: Validate backend imports
        run: |
          echo "Testing backend imports..."
          python3 -c "
          import sys
          try:
              from app.core.config import settings
              print('✅ Config imports successfully')
              print(f'   BASE_DIR: {settings.BASE_DIR}')
              print(f'   Environment: {settings.ENVIRONMENT}')
          except Exception as e:
              print(f'❌ Config import failed: {e}')
              sys.exit(1)
          
          try:
              from app.main import app
              print('✅ FastAPI app imports successfully')
          except Exception as e:
              print(f'❌ FastAPI import failed: {e}')
              sys.exit(1)
          "
          echo "✅ All imports validated"
      
      - name: Run import validation tests
        run: |
          if [ -f "tests/test_imports.py" ]; then
            echo "Running import validation tests..."
            pytest tests/test_imports.py -v --tb=short || {
              echo "⚠️ Some tests failed, but continuing deploy"
              exit 0
            }
            echo "✅ All tests passed"
          else
            echo "ℹ️ No import tests found, skipping..."
          fi
      
      - name: Deploy to Render
        id: deploy
        run: |
          echo "Triggering Render backend deploy..."
          
          response=$(curl -s -w "\n%{http_code}" -X POST \
               "https://api.render.com/v1/services/${{ secrets.RENDER_BACKEND_SERVICE_ID }}/deploys" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
               -H "Content-Type: application/json")
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "Response: $body"
          echo "Status: $http_code"
          
          if [ "$http_code" -ne 201 ] && [ "$http_code" -ne 200 ]; then
            echo "❌ Deploy trigger failed with status $http_code"
            echo "$body" | jq '.' || echo "$body"
            exit 1
          fi
          
          # Extract deploy ID
          deploy_id=$(echo "$body" | jq -r '.id // empty')
          if [ -n "$deploy_id" ]; then
            echo "deploy_id=$deploy_id" >> $GITHUB_OUTPUT
            echo "✅ Deploy triggered successfully (ID: $deploy_id)"
          else
            echo "✅ Deploy triggered successfully"
          fi
      
      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to initialize..."
          echo "ℹ️ This may take 2-5 minutes on Render..."
          
          # Progressive wait: start with longer intervals
          sleep 30
          echo "⏳ 30 seconds elapsed..."
          sleep 30
          echo "⏳ 60 seconds elapsed..."
          sleep 60
          echo "⏳ 120 seconds elapsed..."
      
      - name: Verify deployment
        run: |
          echo "Checking backend health..."
          
          max_attempts=15
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "🔍 Attempt $attempt/$max_attempts..."
            
            # Try health endpoint first
            if curl -f -s --max-time 10 "https://concrete-agent.onrender.com/health" > /dev/null 2>&1; then
              echo "✅ Health endpoint responded!"
              
              # Get health details
              health=$(curl -s "https://concrete-agent.onrender.com/health")
              echo "$health" | jq '.' || echo "$health"
              
              # Test other endpoints
              echo ""
              echo "📊 Testing additional endpoints..."
              
              echo "Testing /status..."
              curl -s "https://concrete-agent.onrender.com/status" | jq '.' || echo "⚠️ /status endpoint not available"
              
              echo "Testing /docs..."
              docs_status=$(curl -s -o /dev/null -w "%{http_code}" "https://concrete-agent.onrender.com/docs")
              if [ "$docs_status" = "200" ]; then
                echo "✅ API docs available at /docs"
              else
                echo "⚠️ /docs returned status $docs_status"
              fi
              
              echo ""
              echo "🎉 Deployment verified successfully!"
              exit 0
            fi
            
            # If health endpoint doesn't exist, try root endpoint
            if curl -f -s --max-time 10 "https://concrete-agent.onrender.com/" > /dev/null 2>&1; then
              echo "✅ Root endpoint responded!"
              echo "⚠️ Note: /health endpoint not available, but service is up"
              exit 0
            fi
            
            echo "⏳ Service not ready yet, waiting 15 seconds..."
            sleep 15
            attempt=$((attempt + 1))
          done
          
          echo "❌ Deployment verification timed out after $((max_attempts * 15)) seconds"
          echo "ℹ️ Check Render logs at: https://dashboard.render.com/web/${{ secrets.RENDER_BACKEND_SERVICE_ID }}"
          exit 1
      
      - name: Deployment summary
        if: always()
        run: |
          echo ""
          echo "=========================================="
          echo "📋 Deployment Summary"
          echo "=========================================="
          echo "Service: concrete-agent"
          echo "URL: https://concrete-agent.onrender.com"
          echo "Docs: https://concrete-agent.onrender.com/docs"
          echo "Dashboard: https://dashboard.render.com/web/${{ secrets.RENDER_BACKEND_SERVICE_ID }}"
          echo ""
          echo "ℹ️ If deployment failed, check Render logs in the dashboard"
          echo "=========================================="
